version: "3.9"

services:
  postgres:
    container_name: postgres_go
    image: postgres:16.4
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: my_pass
      POSTGRES_DB: link
      PGDATA: /data/postgres
    volumes:
      - ./postgres-data:/data/postgres
    ports:
      - "5432:5432"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: shortlink_go
    depends_on:
      - postgres
    ports:
      - "8081:8081"
    environment:
      DSN: "host=postgres user=postgres password=my_pass dbname=link port=5432 sslmode=disable"
      SECRET: "3ZYwtAo1M0rGwiifoASSW4XguJB5FwVJ"