services:
  postgres:
    container_name: postgres_go
    image: postgres:16.4
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: my_pass
      PGDATA: /data/postgres
    volumes:
      - /d/4_SoftwareDevelopment/9_Golang/src/basic_golang/GO-BASICS-6/postgres-data:/data/postgres
    ports:
      - "5432:5432"